apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: student-management-pipeline
spec:
  params:
  - name: git-url
    type: string
    description: Git repository URL
  - name: git-revision
    type: string
    description: Git branch or tag
    default: main
  - name: image-url
    type: string
    description: Image repository URL
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    params:
    - name: url
      value: \$(params.git-url)
    - name: revision
      value: \$(params.git-revision)
  - name: build-and-push
    runAfter:
    - fetch-source
    taskRef:
      name: buildah
    params:
    - name: IMAGE
      value: \$(params.image-url)
    - name: DOCKERFILE
      value: ./Dockerfile
  - name: deploy-application
    runAfter:
    - build-and-push
    taskRef:
      name: kubectl
    params:
    - name: manifests
      value: ./k8s-manifests.yaml
