apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  DB_HOST: "mysql"              # Hostname is the service name of the MySQL Pod
  DB_PORT: "3306"               # Default MySQL port
  DB_NAME: "student_db"         # Database name
